# Generated by Django 5.0.2 on 2024-03-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('binary_field', models.BinaryField()),
                ('boolean_field', models.BooleanField()),
            ],
        ),
    ]
